(() => {
  "use strict";

  const canvas = document.getElementById("game");
  const ctx = canvas.getContext("2d");
  const W = canvas.width;
  const H = canvas.height;
  const RUN_KEY = "brick_block_idle_run_v10";
  const META_KEY = "brick_block_idle_meta_v4";
  const EVO_LEVELS = [10, 25, 50, 100, 200, 500, 1000];

  const rarityInfo = {
    common: { label: "Обычный", rank: 1, color: "#cbd5e1" },
    rare: { label: "Редкий", rank: 2, color: "#38bdf8" },
    epic: { label: "Эпический", rank: 3, color: "#c084fc" },
    legendary: { label: "Легендарный", rank: 4, color: "#facc15" },
  };

  const forms = [
    { key: "striker", rarity: "common", name: "Ударный", color: "#93c5fd", damage: 1.15, speed: 1.0, radius: 1.0, role: "Прямой DPS", desc: "Урон x1.15, скорость x1.00. Стабильный прямой урон без условий. Усиления повышают общий урон через ранг эволюции." },
    { key: "swift", rarity: "common", name: "Быстрый", color: "#67e8f9", damage: 0.75, speed: 1.45, radius: 0.9, role: "Скоростной DPS", desc: "Урон x0.75, скорость x1.45. Больше касаний в секунду, но слабее один удар. Хорош для ранней зачистки." },
    { key: "heavy", rarity: "common", name: "Тяжёлый", color: "#cbd5e1", damage: 1.55, speed: 0.65, radius: 1.15, role: "Тяжёлый удар", desc: "Урон x1.55, скорость x0.65, радиус x1.15. Медленный шар с высоким уроном за попадание." },
    { key: "collector", rarity: "common", name: "Сборщик", color: "#60a5fa", damage: 0.7, speed: 1.05, radius: 1.0, role: "Фарм", desc: "Урон x0.70, скорость x1.05. XP +8% за ранг эволюции, осколки +10% за ранг." },
    { key: "ricochet", rarity: "common", name: "Рикошет", color: "#a7f3d0", damage: 0.9, speed: 1.15, radius: 0.9, role: "Доп. попадания", desc: "Урон x0.90, скорость x1.15. Шанс случайного дополнительного удара: 8% + 1.5% за ранг." },
    { key: "plasma", rarity: "rare", name: "Плазма", color: "#ff4d6d", damage: 0.9, speed: 0.95, radius: 1.05, role: "% урон по области", desc: "Прямой удар добавляет 1.5% + 0.6% за ранг от max HP блока. Сплэш: 1% + 0.5% за ранг от max HP соседних блоков. Радиус: 48px + 14px за ранг." },
    { key: "storm", rarity: "rare", name: "Гроза", color: "#f9f871", damage: 0.8, speed: 1.18, radius: 0.95, role: "Цепная молния", desc: "После добивания бьёт молнией по 1 + ранг случайным блокам, максимум 10. Урон цепи растёт от ранга." },
    { key: "poison", rarity: "rare", name: "Ядовитый", color: "#84cc16", damage: 0.78, speed: 0.9, radius: 1.05, role: "Яд / DoT", desc: "Прямой удар накладывает яд на 4 + 2×ранг секунд. Яд периодически снимает часть max HP и может добивать блоки." },
    { key: "drill", rarity: "rare", name: "Бур", color: "#ff9f1c", damage: 1.35, speed: 0.72, radius: 0.9, role: "Пробитие резистов", desc: "Урон x1.35, скорость x0.72. Частично игнорирует броню, щиты и тяжёлые блоки. Чем выше ранг, тем сильнее пробитие." },
    { key: "crit", rarity: "rare", name: "Крит", color: "#b517ff", damage: 1.05, speed: 1.0, radius: 1.0, role: "Криты", desc: "Шанс крита: 10% + 3% за ранг, максимум 42%. Критический множитель: x1.55 + 0.12 за ранг." },
    { key: "comet", rarity: "rare", name: "Комета", color: "#2ec4b6", damage: 0.92, speed: 1.32, radius: 0.85, role: "Урон от скорости", desc: "Урон x0.92, скорость x1.32. Чем выше скорость шара, тем выше урон. Бонус от скорости ограничен примерно +75%." },
    { key: "frost", rarity: "epic", name: "Ледяной", color: "#bae6fd", damage: 0.95, speed: 0.85, radius: 1.1, role: "Заморозка", desc: "Прямой удар замораживает блок на 2.5 + 0.4×ранг секунд. Замороженный блок не регенерирует и получает больше урона." },
    { key: "vampire", rarity: "epic", name: "Вампирический", color: "#fb7185", damage: 1.0, speed: 1.0, radius: 1.0, role: "Снежный ком", desc: "Каждое добивание даёт временный урон до конца этапа: +1.5% + 0.3% за ранг. Лимит: +120%." },
    { key: "shard", rarity: "epic", name: "Осколочный", color: "#f0abfc", damage: 0.85, speed: 1.05, radius: 1.0, role: "Осколочные удары", desc: "При добивании выпускает 1 + ранг осколочных ударов, максимум 8. Каждый осколок бьёт случайный блок." },
    { key: "gravity", rarity: "epic", name: "Гравитационный", color: "#818cf8", damage: 0.9, speed: 0.9, radius: 1.15, role: "Урон по скоплениям", desc: "После попадания наносит малый урон вокруг точки удара. Радиус: 42px + 9px за ранг." },
    { key: "rift", rarity: "epic", name: "Разлом", color: "#c084fc", damage: 1.1, speed: 0.8, radius: 1.05, role: "Линейный урон", desc: "После попадания дополнительно повреждает блоки в той же горизонтальной линии. Количество целей растёт от ранга." },
    { key: "singularity", rarity: "legendary", name: "Сингулярный", color: "#facc15", damage: 1.05, speed: 0.85, radius: 1.2, role: "Финишер поля", desc: "Чем меньше блоков осталось, тем выше урон. Лучше всего добивает конец этапа." },
    { key: "quantum", rarity: "legendary", name: "Квантовый", color: "#22d3ee", damage: 1.05, speed: 1.1, radius: 1.0, role: "Случайные цели", desc: "При попадании имеет шанс ударить случайный дополнительный блок: 4% + 1.5% за ранг." },
    { key: "solar", rarity: "legendary", name: "Солнечный", color: "#f97316", damage: 1.2, speed: 0.75, radius: 1.25, role: "Вспышка", desc: "Периодически добавляет процентный урон от max HP блока. Чем выше ранг, тем чаще и сильнее вспышка." },
    { key: "royal", rarity: "legendary", name: "Королевский", color: "#eab308", damage: 0.65, speed: 0.95, radius: 1.0, role: "Аура поддержки", desc: "Сам слабее, но каждый ранг даёт остальным шарам +2.5% урона. Несколько аур суммируются." },
    { key: "sniper", rarity: "legendary", name: "Снайпер", color: "#e5e7eb", damage: 1.15, speed: 0.95, radius: 0.82, role: "Автонаведение от стены", desc: "После каждого отскока от стены шар перенаправляется прямо в ближайший блок." },
    { key: "berserk", rarity: "legendary", name: "Берсерк", color: "#ef4444", damage: 0.9, speed: 1.0, radius: 1.0, role: "Бесконечный разгон этапа", desc: "За каждое уничтожение блока получает +3.5% + 0.8% за ранг к скорости до конца этапа. Верхнего лимита нет. При смене этапа бонус сбрасывается." },
    { key: "infinite", rarity: "legendary", name: "Бесконечный", color: "#ffffff", damage: 1.0, speed: 1.0, radius: 1.0, role: "Случайный рост", desc: "Каждое усиление случайно даёт +5% к одному постоянному бонусу: урон, скорость, XP или осколки." },
  ];

  const brickTypes = [
    { key: "normal", name: "Обычный", color: "#4cc9f0", min: 1, weight: 100, reward: 1, info: "Без резистов и спецэффектов." },
    { key: "armored", name: "Броня", color: "#94a3b8", min: 5, weight: 14, reward: 1.25, info: "Режет прямой урон. Бур частично игнорирует штраф." },
    { key: "volatile", name: "Нестабильный", color: "#ff9f1c", min: 10, weight: 8, reward: 1.15, info: "При уничтожении взрывается и повреждает соседние блоки." },
    { key: "regen", name: "Живой", color: "#2ec4b6", min: 18, weight: 8, reward: 1.35, info: "Постепенно восстанавливает HP, если не заморожен." },
    { key: "shield", name: "Щит", color: "#b517ff", min: 25, weight: 7, reward: 1.5, info: "Сильно режет непрямой урон: сплэш, цепи и взрывы." },
    { key: "heavy", name: "Тяжёлый", color: "#ff4d6d", min: 40, weight: 5, reward: 1.75, info: "Сильно режет прямой урон, но даёт повышенную награду." },
  ];

  const metaNodes = [
    { id: "dmg1", row: 1, name: "Калибровка урона I", type: "normal", max: 5, cost: 1, effect: { damage: 1 }, desc: "+1 постоянный уровень урона." },
    { id: "spd1", row: 1, name: "Магнитный разгон I", type: "normal", max: 4, cost: 1, effect: { speed: 1 }, desc: "+1 постоянный уровень скорости." },
    { id: "xp1", row: 1, name: "Память ядра I", type: "normal", max: 4, cost: 1, effect: { xp: 1 }, desc: "+1 постоянный уровень опыта." },
    { id: "frag1", row: 1, name: "Стартовый запас I", type: "normal", max: 5, cost: 1, effect: { startFragments: 40 }, desc: "+40 стартовых осколков." },
    { id: "firstExtra", row: 2, name: "Экстра: стартовый импульс", type: "extra", max: 1, cost: 4, req: ["dmg1", "frag1"], effect: { startFragments: 180, damage: 1 }, desc: "+180 стартовых осколков и +1 постоянный уровень урона." },
    { id: "dmg2", row: 3, name: "Калибровка урона II", type: "normal", max: 7, cost: 2, req: ["dmg1"], effect: { damage: 1 }, desc: "+1 постоянный уровень урона за ранг." },
    { id: "spd2", row: 3, name: "Магнитный разгон II", type: "normal", max: 6, cost: 2, req: ["spd1"], effect: { speed: 1 }, desc: "+1 постоянный уровень скорости за ранг." },
    { id: "xp2", row: 3, name: "Память ядра II", type: "normal", max: 6, cost: 2, req: ["xp1"], effect: { xp: 1 }, desc: "+1 постоянный уровень XP за ранг." },
    { id: "frag2", row: 3, name: "Стартовый запас II", type: "normal", max: 6, cost: 2, req: ["frag1"], effect: { startFragments: 70 }, desc: "+70 стартовых осколков за ранг." },
    { id: "autoEvolution", row: 4, name: "Экстра: автоэволюция", type: "extra", max: 1, cost: 7, req: ["xp2"], effect: { autoEvolution: 1 }, desc: "Автоматически выбирает самый редкий вариант эволюции." },
    { id: "dmg3", row: 5, name: "Калибровка урона III", type: "normal", max: 8, cost: 4, req: ["dmg2"], effect: { damage: 1 }, desc: "+1 постоянный уровень урона за ранг." },
    { id: "spd3", row: 5, name: "Магнитный разгон III", type: "normal", max: 7, cost: 4, req: ["spd2"], effect: { speed: 1 }, desc: "+1 постоянный уровень скорости за ранг." },
    { id: "xp3", row: 5, name: "Память ядра III", type: "normal", max: 8, cost: 4, req: ["xp2"], effect: { xp: 1 }, desc: "+1 постоянный уровень XP за ранг." },
    { id: "starterBall3", row: 6, name: "Экстра: третий стартовый шар", type: "extra", max: 1, cost: 12, req: ["firstExtra", "dmg2"], effect: { starterBalls: 1 }, desc: "Новый забег начинается с дополнительным обычным шаром." },
    { id: "prestige1", row: 7, name: "Резонанс сингулярности I", type: "normal", max: 5, cost: 5, req: ["autoEvolution"], effect: { prestigeBoost: 0.08 }, desc: "+8% ядер за сингулярность за ранг." },
    { id: "discount1", row: 7, name: "Стабилизация цен I", type: "normal", max: 5, cost: 5, req: ["starterBall3"], effect: { discount: 0.03 }, desc: "-3% к цене временных апгрейдов за ранг." },
    { id: "stageSkip1", row: 8, name: "Экстра: пропуск разгона", type: "extra", max: 1, cost: 18, req: ["prestige1", "discount1"], effect: { startLevel: 3 }, desc: "Новый забег начинается с 3 этапа." },
    { id: "dmg4", row: 9, name: "Калибровка урона IV", type: "normal", max: 10, cost: 8, req: ["dmg3"], effect: { damage: 1 }, desc: "+1 постоянный уровень урона за ранг." },
    { id: "spd4", row: 9, name: "Магнитный разгон IV", type: "normal", max: 8, cost: 8, req: ["spd3"], effect: { speed: 1 }, desc: "+1 постоянный уровень скорости за ранг." },
    { id: "xp4", row: 9, name: "Память ядра IV", type: "normal", max: 10, cost: 8, req: ["xp3"], effect: { xp: 1 }, desc: "+1 постоянный уровень XP за ранг." },
    { id: "starterBall4", row: 10, name: "Экстра: четвёртый стартовый шар", type: "extra", max: 1, cost: 28, req: ["starterBall3", "dmg4"], effect: { starterBalls: 2 }, desc: "Новый забег начинается ещё с одним обычным шаром." },
    { id: "prestige2", row: 11, name: "Резонанс сингулярности II", type: "normal", max: 8, cost: 10, req: ["prestige1"], effect: { prestigeBoost: 0.1 }, desc: "+10% ядер за сингулярность за ранг." },
    { id: "stageSkip2", row: 12, name: "Экстра: боевой старт", type: "extra", max: 1, cost: 42, req: ["stageSkip1", "prestige2"], effect: { startLevel: 6, startFragments: 600 }, desc: "Новый забег начинается с 6 этапа и +600 осколков." },
    { id: "coreBank", row: 12, name: "Экстра: банк ядра", type: "extra", max: 1, cost: 55, req: ["discount1", "prestige2"], effect: { bank: 1 }, desc: "10% осколков сохраняются в следующий забег после сингулярности." },
    { id: "rareLuck", row: 13, name: "Удача редкости I", type: "normal", max: 10, cost: 12, req: ["autoEvolution"], effect: { rareLuck: 1 }, desc: "Повышает шанс редких, эпических и легендарных вариантов." },
    { id: "startRare", row: 13, name: "Экстра: редкий старт", type: "extra", max: 1, cost: 75, req: ["coreBank"], effect: { startRare: 1 }, desc: "Новый забег начинается с одним редким шаром." },
    { id: "choicePlus", row: 14, name: "Широкий выбор", type: "extra", max: 1, cost: 95, req: ["rareLuck"], effect: { choiceBonus: 1 }, desc: "+1 вариант при выборе архетипа." },
    { id: "startEpic", row: 14, name: "Экстра: эпический старт", type: "extra", max: 1, cost: 140, req: ["startRare", "starterBall4"], effect: { startEpic: 1 }, desc: "Новый забег начинается с одним эпическим шаром." },
    { id: "startLegendary", row: 15, name: "Экстра: легендарный старт", type: "extra", max: 1, cost: 260, req: ["startEpic", "prestige2"], effect: { startLegendary: 1 }, desc: "Новый забег начинается с одним легендарным шаром." },
  ];

  const state = { level: 1, fragments: 0, total: 0, paused: false, bricks: [], balls: [], upgrades: { damage: 1, speed: 0, xp: 0 }, log: ["v10: стабильная сборка без loader-цепочек."] };
  const uiCache = new Map();
  let frame = 0;
  let lastSaveFrame = 0;

  const el = (id) => document.getElementById(id);
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const safeNum = (value) => Number.isFinite(Number(value)) ? Number(value) : 0;
  function setHTML(id, html) { if (uiCache.get(id) === html) return; uiCache.set(id, html); const node = el(id); if (node) node.innerHTML = html; }
  function setText(id, text) { const node = el(id); if (!node) return; const value = String(text); if (node.textContent !== value) node.textContent = value; }
  function rng(seed) { let value = seed % 2147483647; if (value <= 0) value += 2147483646; return () => { value = (value * 16807) % 2147483647; return (value - 1) / 2147483646; }; }
  function log(text) { state.log = [text, ...state.log].slice(0, 9); renderLog(); }
  function getMeta() { try { const meta = JSON.parse(localStorage.getItem(META_KEY)); return normalizeMeta(meta && typeof meta === "object" ? meta : {}); } catch { return normalizeMeta({}); } }
  function normalizeMeta(meta) { meta.cores = safeNum(meta.cores); meta.spent = safeNum(meta.spent); meta.bankedFragments = safeNum(meta.bankedFragments); meta.nodes = meta.nodes && typeof meta.nodes === "object" ? meta.nodes : {}; return meta; }
  function setMeta(meta) { localStorage.setItem(META_KEY, JSON.stringify(normalizeMeta(meta))); }
  function metaRank(meta, id) { return safeNum(meta.nodes[id]); }
  function metaUnlocked(meta, node) { return !node.req || node.req.every((id) => metaRank(meta, id) > 0); }
  function metaNodeCost(node, level) { return Math.ceil(node.cost * Math.pow(1.62, level)); }
  function metaEffects() { const meta = getMeta(); const out = { damage: 0, speed: 0, xp: 0, startFragments: 0, autoEvolution: 0, starterBalls: 0, prestigeBoost: 0, discount: 0, startLevel: 1, bank: 0, startRare: 0, startEpic: 0, startLegendary: 0, rareLuck: 0, choiceBonus: 0 }; for (const node of metaNodes) { const level = metaRank(meta, node.id); if (!level) continue; for (const [key, value] of Object.entries(node.effect)) { if (key === "startLevel") out.startLevel = Math.max(out.startLevel, value); else if (key === "starterBalls") out.starterBalls = Math.max(out.starterBalls, value); else if (["autoEvolution", "bank", "startRare", "startEpic", "startLegendary", "choiceBonus"].includes(key)) out[key] = Math.max(out[key], value); else out[key] += value * level; } } return out; }
  function activeTypes() { return brickTypes.filter((type) => state.level >= type.min); }
  function effectiveUpgrade(key) { const eff = metaEffects(); return (state.upgrades[key] || 0) + (eff[key] || 0); }
  function stageHp(level) { return Math.max(1, Math.floor(1 + level * 0.75 + Math.pow(Math.max(0, level - 25), 1.18) * 0.28 + Math.pow(Math.max(0, level - 250), 1.32) * 0.06)); }
  function brickReward(level, typeReward) { return Math.ceil((2 + level * 0.75 + Math.pow(level, 1.08) * 0.35) * typeReward); }
  function upgradePower(level, kind) { if (level <= 0) return 1; const linear = kind === "speed" ? 0.34 : kind === "xp" ? 0.38 : 0.46; const curve = kind === "speed" ? 0.08 : kind === "xp" ? 0.1 : 0.14; return +(1 + level * linear + (Math.pow(level, 1.28) - level) * curve).toFixed(2); }
  function xpNeed(level) { if (level <= 1) return 32; return Math.floor(32 + level * 18 + Math.pow(level, 1.52) * 10 + Math.pow(Math.max(0, level - 20), 1.82) * 8 + (EVO_LEVELS.includes(level) ? level * 70 : 0)); }
  function pendingMilestone(ball) { return EVO_LEVELS.find((level) => ball.level >= level && !ball.evolved.includes(level)) || null; }
  function isEvolutionLocked(ball) { return Boolean(ball.pendingEvolution || pendingMilestone(ball)); }
  function formStats(ball) { return forms.find((form) => form.key === ball.form) || { key: "basic", rarity: "common", damage: 1, speed: 1, radius: 1, name: "Базовый", color: "#4cc9f0", role: "Нет архетипа", desc: "На 10 уровне выберет первый архетип." }; }
  function rarityRank(rarity) { return rarityInfo[rarity]?.rank || 1; }
  function royalBuff(excludeId = null) { return state.balls.reduce((sum, ball) => ball.id === excludeId || ball.form !== "royal" ? sum : sum + ball.evo * 0.025, 0); }
  function damageFor(ball) { const stats = formStats(ball); const rarityBonus = 1 + (rarityRank(stats.rarity) - 1) * 0.08; const infiniteBonus = ball.infiniteDamage || 0; const stagePower = ball.stagePower || 0; const base = 1 + (ball.level - 1) * 0.25 + Math.pow(ball.level - 1, 1.05) * 0.045; const evo = 1 + ball.evo * 0.16 + Math.pow(ball.evo, 1.18) * 0.03; return +(base * evo * rarityBonus * (stats.damage || 1) * (1 + stagePower) * (1 + infiniteBonus) * (1 + royalBuff(ball.id)) * upgradePower(effectiveUpgrade("damage"), "damage")).toFixed(2); }
  function personalSpeed(ball) { const stats = formStats(ball); const comet = ball.form === "comet" ? ball.evo * 0.02 : 0; const infiniteSpeed = ball.infiniteSpeed || 0; const berserk = ball.form === "berserk" ? (ball.berserkSpeed || 0) : 0; const raw = (1 + (ball.level - 1) * 0.0042 + ball.evo * 0.02 + comet + infiniteSpeed + berserk) * (stats.speed || 1); return ball.form === "berserk" ? Math.max(0.55, raw) : clamp(raw, 0.55, 3.2); }
  function totalSpeed(ball) { return personalSpeed(ball) * upgradePower(effectiveUpgrade("speed"), "speed"); }
  function xpMult() { return upgradePower(effectiveUpgrade("xp"), "xp"); }
  function xpGain(brick, ball, manual = false) { if (!ball || isEvolutionLocked(ball)) return 0; const collector = ball.form === "collector" ? 1 + ball.evo * 0.08 : 1; const infinite = 1 + (ball.infiniteXp || 0); const stageXpBonus = 1 + Math.pow(Math.max(1, state.level), 0.45) * 0.035; const manualPenalty = manual ? 0.45 : 1; return Math.max(1, Math.ceil(brick.xp * 0.08 * xpMult() * collector * infinite * stageXpBonus * manualPenalty)); }
  function fragGain(brick, ball) { const collector = ball?.form === "collector" ? 1 + ball.evo * 0.1 : 1; const infinite = 1 + (ball?.infiniteFragments || 0); return Math.max(1, Math.ceil(brick.xp * 0.34 * collector * infinite)); }
  function discount() { return clamp(metaEffects().discount || 0, 0, 0.65); }
  function ballCost() { return Math.floor(180 * Math.pow(1.78, Math.max(0, state.balls.length - 2)) * (1 - discount())); }
  function upgradeCost(key) { const base = key === "damage" ? 95 : key === "speed" ? 130 : 150; const growth = key === "damage" ? 1.62 : key === "speed" ? 1.7 : 1.74; const level = state.upgrades[key] || 0; return Math.floor(base * Math.pow(growth, level + Math.pow(level, 1.18) * 0.34) * (1 - discount())); }
  function normalize(ball) { const len = Math.hypot(ball.dx, ball.dy) || 1; ball.dx /= len; ball.dy /= len; }
  function makeBall(id, index, saved = {}) { const angle = -Math.PI / 4 - index * 0.33; const ball = { id, level: 1, x: W / 2 + index * 34, y: H - 86 - index * 18, dx: Math.cos(angle) * (index % 2 ? -1 : 1), dy: -Math.abs(Math.sin(angle)), r: 9, xp: 0, need: 32, kills: 0, hits: 0, evo: 0, form: "basic", formName: "Базовый", rarity: "common", color: "#4cc9f0", evolved: [], pendingEvolution: null, stagePower: 0, berserkSpeed: 0, ...saved }; if (typeof ball.dx !== "number" || typeof ball.dy !== "number") { ball.dx = Math.cos(angle) * (index % 2 ? -1 : 1); ball.dy = -Math.abs(Math.sin(angle)); } normalize(ball); ball.need = xpNeed(ball.level); ball.pendingEvolution = ball.pendingEvolution || pendingMilestone(ball); ball.dmg = damageFor(ball); return ball; }

  function weightedForm(random) { const luck = metaEffects().rareLuck || 0; const weights = { common: Math.max(25, 55 - luck * 2), rare: 28 + luck * 1.2, epic: 13 + luck * 0.65, legendary: 4 + luck * 0.18 }; const total = Object.values(weights).reduce((sum, value) => sum + value, 0); let roll = random() * total; let rarity = "common"; for (const key of ["common", "rare", "epic", "legendary"]) { roll -= weights[key]; if (roll <= 0) { rarity = key; break; } } const pool = forms.filter((form) => form.rarity === rarity); return pool[Math.floor(random() * pool.length)] || forms[0]; }
  function chooseForms(ball) { const random = rng(Date.now() + ball.id * 1337 + ball.level * 17 + state.level * 31); const target = 3 + (metaEffects().choiceBonus || 0); const result = []; while (result.length < target && result.length < forms.length) { const form = weightedForm(random); if (!result.some((item) => item.key === form.key)) result.push(form); } return result.sort((a, b) => rarityRank(b.rarity) - rarityRank(a.rarity)); }
  function pickStarterForm(rarity, index) { const pool = forms.filter((form) => form.rarity === rarity); return pool[index % pool.length] || pool[0] || forms[0]; }
  function forceBallForm(ball, form) { if (!ball || !form) return; ball.form = form.key; ball.formName = form.name; ball.color = form.color; ball.rarity = form.rarity; ball.evo = Math.max(ball.evo || 0, 1); ball.r = 9 + Math.min(12, ball.evo * 0.95) * (form.radius || 1); ball.evolved = ball.evolved || []; if (!ball.evolved.includes(10)) ball.evolved.push(10); ball.pendingEvolution = null; ball.dmg = damageFor(ball); }
  function applyEvolution(ballId, formKey) { const ball = state.balls.find((item) => item.id === ballId); const form = forms.find((item) => item.key === formKey); if (!ball || !form) return; const milestone = ball.pendingEvolution || pendingMilestone(ball); if (!milestone) return; if (ball.form !== "basic") { const current = formStats(ball); ball.evo += 1; ball.evolved.push(milestone); ball.pendingEvolution = null; ball.xp = 0; ball.need = xpNeed(ball.level); if (ball.form === "infinite") { const roll = ["infiniteDamage", "infiniteSpeed", "infiniteXp", "infiniteFragments"][Math.floor(Math.random() * 4)]; ball[roll] = (ball[roll] || 0) + 0.05; } ball.r = 9 + Math.min(12, ball.evo * 0.95) * (current.radius || 1); ball.dmg = damageFor(ball); log(`Шар-${ball.id}: усилена форма ${current.name}.`); return; } ball.evo = 1; ball.form = form.key; ball.formName = form.name; ball.color = form.color; ball.rarity = form.rarity; ball.r = 9 + Math.min(12, ball.evo * 0.95) * (form.radius || 1); ball.evolved.push(milestone); ball.pendingEvolution = null; ball.xp = 0; ball.need = xpNeed(ball.level); ball.dmg = damageFor(ball); log(`Шар-${ball.id}: ${rarityInfo[form.rarity].label} ${form.name}.`); }
  function showEvolution(ballId) { const ball = state.balls.find((item) => item.id === ballId); if (!ball) return; const milestone = ball.pendingEvolution || pendingMilestone(ball); if (!milestone) return; if (ball.form !== "basic") { applyEvolution(ball.id, ball.form); renderAllUI(true); return; } const choices = chooseForms(ball); if (metaEffects().autoEvolution) { applyEvolution(ball.id, choices[0].key); renderAllUI(true); return; } ball.pendingEvolution = milestone; document.querySelector(".evo-modal")?.remove(); const modal = document.createElement("div"); modal.className = "evo-modal"; modal.innerHTML = `<div class="evo-box"><h2>Архетип Шара-${ball.id}</h2><p>Шар достиг ${milestone} уровня. Выбери специализацию. Следующие эволюции будут усиливать этот же тип.</p><div class="evo-grid">${choices.map((form) => `<button class="evo-choice evo-${form.rarity}" data-ball="${ball.id}" data-form="${form.key}"><span class="dot" style="background:${form.color}"></span><b>${rarityInfo[form.rarity].label}: ${form.name}</b><small>${form.desc}<br><br><b>Роль:</b> ${form.role}.<br><b>Статы:</b> урон x${form.damage}, скорость x${form.speed}, радиус x${form.radius}.</small></button>`).join("")}</div><button class="control evo-close">Позже</button></div>`; modal.addEventListener("pointerdown", (event) => { const choice = event.target.closest(".evo-choice"); if (choice) { applyEvolution(Number(choice.dataset.ball), choice.dataset.form); modal.remove(); renderAllUI(true); return; } if (event.target.closest(".evo-close")) modal.remove(); }); document.body.appendChild(modal); }

  function pattern(row, col, rows, cols) { if (state.level === 1) return true; if (row === 0 || row === rows - 1) return true; const p = (state.level - 1) % 8; const cx = (cols - 1) / 2; const cy = (rows - 1) / 2; const dx = col - cx; const dy = row - cy; const distance = Math.hypot(dx, dy); const angle = Math.atan2(dy, dx); if (p === 0) return !((col + state.level) % 5 === 0 && row % 4 !== 0); if (p === 1) return (row + col + state.level) % 6 !== 0 && (row * 2 + col + state.level) % 11 !== 0; if (p === 2) return Math.abs((distance + state.level * 0.35) % 4) > 0.85; if (p === 3) return Math.hypot(col - cols * 0.32, row - rows * 0.48) > 2.4 && Math.hypot(col - cols * 0.68, row - rows * 0.48) > 2.4; if (p === 4) return row % 4 !== 2 || (col + state.level) % 4 !== 0; if (p === 5) return Math.abs(Math.sin(angle * 2.4 + distance * 0.68 + state.level * 0.25)) > 0.26; if (p === 6) return (row + col * 2 + state.level) % 7 !== 0; return rng(state.level * 999 + row * 13 + col)() > 0.14; }
  function pickType(row, col, random) { const pool = activeTypes(); if (pool.length === 1) return pool[0]; const weighted = pool.map((type) => ({ type, weight: type.key === "normal" ? Math.max(42, type.weight - state.level * 0.65) : type.weight + ((row * 11 + col * 7 + state.level) % 9) * 0.2 })); let roll = random() * weighted.reduce((sum, item) => sum + item.weight, 0); for (const item of weighted) { roll -= item.weight; if (roll <= 0) return item.type; } return pool[0]; }
  function generateBricks() { const cols = clamp(24 + Math.floor(state.level / 12), 24, 32); const gap = 4; const marginX = 16; const top = 62; const brickH = 21; const rows = Math.floor((H - 20 - top + gap) / (brickH + gap)); const brickW = (W - marginX * 2 - gap * (cols - 1)) / cols; const random = rng(state.level * 9973 + 41); const hp = stageHp(state.level); state.bricks = []; for (let row = 0; row < rows; row += 1) { for (let col = 0; col < cols; col += 1) { if (!pattern(row, col, rows, cols)) continue; const type = pickType(row, col, random); state.bricks.push({ x: marginX + col * (brickW + gap), y: top + row * (brickH + gap), w: brickW, h: brickH, hp, max: hp, xp: brickReward(state.level, type.reward), type: type.key, name: type.name, color: type.color, poison: 0, poisonOwner: null, frozen: 0 }); } } }
  function damageMult(ball, brick, source) { let mult = 1; if (brick.type === "armored") mult = source === "direct" ? 0.55 : 0.75; if (brick.type === "regen") mult = source === "direct" ? 0.85 : 0.7; if (brick.type === "shield") mult = source === "direct" ? 0.8 : 0.35; if (brick.type === "heavy") mult = source === "direct" ? 0.45 : 0.58; if (brick.frozen > 0) mult += 0.12 + ball.evo * 0.012; if (ball.form === "drill" && source === "direct" && mult < 1) mult += (1 - mult) * clamp(0.35 + ball.evo * 0.08, 0.35, 0.88); return mult; }
  function reward(ball, brick, manual = false) { const target = ball || state.balls.filter((item) => !isEvolutionLocked(item)).sort((a, b) => a.level - b.level || a.xp - b.xp)[0]; state.fragments += fragGain(brick, target); state.total += 1; if (!target) return; if (!manual) target.kills += 1; if (target.form === "vampire") { target.stagePower = Math.min(1.2, (target.stagePower || 0) + 0.015 + target.evo * 0.003); target.dmg = damageFor(target); } if (!manual && target.form === "berserk") target.berserkSpeed = (target.berserkSpeed || 0) + 0.035 + target.evo * 0.008; if (isEvolutionLocked(target)) { if (metaEffects().autoEvolution) showEvolution(target.id); return; } target.xp += xpGain(brick, target, manual); while (!isEvolutionLocked(target) && target.xp >= target.need) { target.xp -= target.need; target.level += 1; target.need = xpNeed(target.level); target.dmg = damageFor(target); log(`Шар-${target.id}: ${target.level} ур.`); const milestone = pendingMilestone(target); if (milestone) { target.pendingEvolution = milestone; target.xp = 0; log(`Шар-${target.id} ждёт эволюцию ${milestone} ур.`); if (metaEffects().autoEvolution) showEvolution(target.id); break; } } }
  function dealDamage(index, amount, ball, source = "direct") { const brick = state.bricks[index]; if (!brick || !ball) return false; if (ball.form === "poison" && source === "direct") { brick.poison = Math.max(brick.poison || 0, 4 + ball.evo * 2); brick.poisonOwner = ball.id; } if (ball.form === "frost" && source === "direct") brick.frozen = Math.max(brick.frozen || 0, 2.5 + ball.evo * 0.4); brick.hp -= amount * damageMult(ball, brick, source); if (brick.hp > 0) return false; const destroyed = state.bricks.splice(index, 1)[0]; if (!destroyed) return false; reward(ball, destroyed); if (destroyed.type === "volatile") { const cx = destroyed.x + destroyed.w / 2; const cy = destroyed.y + destroyed.h / 2; const targets = state.bricks.map((candidate, targetIndex) => ({ targetIndex, distance: Math.hypot(candidate.x + candidate.w / 2 - cx, candidate.y + candidate.h / 2 - cy) })).filter((item) => item.distance <= 62).map((item) => item.targetIndex).sort((a, b) => b - a); for (const target of targets) dealDamage(target, Math.max(1, stageHp(state.level) * 0.12 + ball.dmg * 0.12), ball, "explosion"); } return true; }
  function hitDamage(ball, brick) { let amount = ball.dmg; if (ball.form === "plasma") amount += Math.max(1, brick.max * (0.015 + ball.evo * 0.006)); if (ball.form === "singularity") amount *= 1 + Math.max(0, 1 - state.bricks.length / 120) * (0.8 + ball.evo * 0.18); if (ball.form === "crit" && Math.random() < clamp(0.1 + ball.evo * 0.03, 0.1, 0.42)) amount *= 1.55 + ball.evo * 0.12; if (ball.form === "drill" && brick.hp / brick.max > 0.5) amount *= 1.18 + ball.evo * 0.1; if (ball.form === "comet") amount *= 1 + Math.min(0.75, (personalSpeed(ball) - 1) * 0.22); if (ball.form === "solar" && ball.hits % Math.max(12, 34 - ball.evo * 3) === 0) amount += brick.max * (0.03 + ball.evo * 0.006); return amount; }
  function collide(ball, brick) { const nearestX = clamp(ball.x, brick.x, brick.x + brick.w); const nearestY = clamp(ball.y, brick.y, brick.y + brick.h); const dx = ball.x - nearestX; const dy = ball.y - nearestY; return dx * dx + dy * dy <= ball.r * ball.r; }
  function aimAtNearestBlock(ball) { if (!state.bricks.length) return; let best = null; let bestDistance = Infinity; for (const brick of state.bricks) { const tx = brick.x + brick.w / 2; const ty = brick.y + brick.h / 2; const distance = Math.hypot(tx - ball.x, ty - ball.y); if (distance < bestDistance) { bestDistance = distance; best = { x: tx, y: ty }; } } if (!best) return; ball.dx = best.x - ball.x; ball.dy = best.y - ball.y; normalize(ball); }
  function processAreaDamage(ball, center, destroyed) { if (ball.form === "plasma" && ball.evo > 0) { const targets = state.bricks.map((brick, index) => ({ index, distance: Math.hypot(brick.x + brick.w / 2 - center.x, brick.y + brick.h / 2 - center.y) })).filter((item) => item.distance <= 48 + ball.evo * 14).map((item) => item.index).sort((a, b) => b - a); for (const target of targets) { const brick = state.bricks[target]; if (brick) dealDamage(target, Math.max(1, brick.max * (0.01 + ball.evo * 0.005)), ball, "splash"); } } if (ball.form === "gravity" && ball.evo > 0) { const targets = state.bricks.map((brick, index) => ({ index, distance: Math.hypot(brick.x + brick.w / 2 - center.x, brick.y + brick.h / 2 - center.y) })).filter((item) => item.distance <= 42 + ball.evo * 9).map((item) => item.index).sort((a, b) => b - a); for (const target of targets) dealDamage(target, ball.dmg * (0.05 + ball.evo * 0.01), ball, "gravity"); } if (ball.form === "rift" && ball.evo > 0) { const targets = state.bricks.map((brick, index) => ({ index, sameRow: Math.abs(brick.y - center.y) <= 14 })).filter((item) => item.sameRow).slice(0, 4 + ball.evo).map((item) => item.index).sort((a, b) => b - a); for (const target of targets) dealDamage(target, ball.dmg * (0.09 + ball.evo * 0.015), ball, "rift"); } if (destroyed && ball.form === "storm" && state.bricks.length > 0) { const jumps = clamp(1 + ball.evo, 1, 10); for (let n = 0; n < jumps && state.bricks.length > 0; n += 1) dealDamage(Math.floor(Math.random() * state.bricks.length), ball.dmg * (0.32 + ball.evo * 0.04), ball, "chain"); } if (destroyed && ball.form === "shard") { const shots = clamp(1 + ball.evo, 1, 8); for (let n = 0; n < shots && state.bricks.length > 0; n += 1) dealDamage(Math.floor(Math.random() * state.bricks.length), ball.dmg * 0.22, ball, "shard"); } if (ball.form === "quantum" && Math.random() < 0.04 + ball.evo * 0.015 && state.bricks.length > 0) dealDamage(Math.floor(Math.random() * state.bricks.length), ball.dmg * 0.8, ball, "quantum"); if (ball.form === "ricochet" && Math.random() < 0.08 + ball.evo * 0.015 && state.bricks.length > 0) dealDamage(Math.floor(Math.random() * state.bricks.length), ball.dmg * 0.4, ball, "ricochet"); }
  function processBrickStatuses() { for (let index = state.bricks.length - 1; index >= 0; index -= 1) { const brick = state.bricks[index]; if (brick.frozen > 0) brick.frozen -= 1 / 60; if (brick.poison > 0) { brick.poison -= 1 / 60; brick.hp -= Math.max(0.015, brick.max * 0.0008); if (brick.hp <= 0) { const poisonOwner = state.balls.find((ball) => ball.id === brick.poisonOwner) || state.balls.find((ball) => ball.form === "poison") || state.balls[0]; const destroyed = state.bricks.splice(index, 1)[0]; if (poisonOwner && destroyed) reward(poisonOwner, destroyed); continue; } } if (brick.type === "regen" && brick.hp < brick.max && brick.frozen <= 0) brick.hp = Math.min(brick.max, brick.hp + Math.max(0.01, stageHp(state.level) * 0.001)); } }
  function step() { if (state.paused) return; processBrickStatuses(); for (const ball of state.balls) { const move = 1.15 * totalSpeed(ball); ball.x += ball.dx * move; ball.y += ball.dy * move; let bouncedWall = false; if (ball.x - ball.r <= 0 || ball.x + ball.r >= W) { ball.dx *= -1; ball.x = clamp(ball.x, ball.r, W - ball.r); bouncedWall = true; } if (ball.y - ball.r <= 0 || ball.y + ball.r >= H) { ball.dy *= -1; ball.y = clamp(ball.y, ball.r, H - ball.r); bouncedWall = true; } normalize(ball); if (bouncedWall && ball.form === "sniper") aimAtNearestBlock(ball); for (let index = state.bricks.length - 1; index >= 0; index -= 1) { const brick = state.bricks[index]; if (!brick || !collide(ball, brick)) continue; const prevX = ball.x - ball.dx * move; const prevY = ball.y - ball.dy * move; const center = { x: brick.x + brick.w / 2, y: brick.y + brick.h / 2 }; ball.x = prevX; ball.y = prevY; const hitFromSide = prevX < brick.x || prevX > brick.x + brick.w; const hitFromVertical = prevY < brick.y || prevY > brick.y + brick.h; if (hitFromSide && hitFromVertical) { const relativeX = Math.abs(prevX - center.x) / Math.max(1, brick.w / 2); const relativeY = Math.abs(prevY - center.y) / Math.max(1, brick.h / 2); if (relativeX > relativeY) ball.dx *= -1; else ball.dy *= -1; } else if (hitFromSide) ball.dx *= -1; else ball.dy *= -1; ball.x += ball.dx * 0.75; ball.y += ball.dy * 0.75; normalize(ball); ball.hits += 1; const destroyed = dealDamage(index, hitDamage(ball, brick), ball); processAreaDamage(ball, center, destroyed); break; } } if (state.bricks.length === 0) { state.level += 1; generateBricks(); for (const ball of state.balls) { ball.stagePower = 0; ball.berserkSpeed = 0; ball.dmg = damageFor(ball); normalize(ball); } log(`Открыт этап ${state.level}. HP блока: ${stageHp(state.level)}.`); renderAllUI(true); } }
  function manualHitAt(x, y) { for (let index = state.bricks.length - 1; index >= 0; index -= 1) { const brick = state.bricks[index]; if (!brick) continue; if (x < brick.x || x > brick.x + brick.w || y < brick.y || y > brick.y + brick.h) continue; brick.hp -= 1; if (brick.hp <= 0) { const destroyed = state.bricks.splice(index, 1)[0]; const target = state.balls.filter((ball) => !isEvolutionLocked(ball)).sort((a, b) => a.level - b.level || a.xp - b.xp)[0]; reward(target, destroyed, true); } renderAllUI(true); return true; } return false; }

  function rr(x, y, w, h, radius) { ctx.beginPath(); ctx.roundRect(x, y, w, h, radius); }
  function draw() { ctx.clearRect(0, 0, W, H); const bg = ctx.createLinearGradient(0, 0, 0, H); bg.addColorStop(0, "#070b18"); bg.addColorStop(1, "#111827"); ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H); ctx.fillStyle = "rgba(148,163,184,.08)"; for (let x = 22; x < W; x += 42) for (let y = 76; y < H; y += 42) { ctx.beginPath(); ctx.arc(x, y, 1.45, 0, Math.PI * 2); ctx.fill(); } rr(22, 16, W - 44, 38, 16); ctx.fillStyle = "rgba(15,23,42,.82)"; ctx.fill(); ctx.fillStyle = "#fff"; ctx.font = "900 18px system-ui"; ctx.fillText(`Этап ${state.level}`, 42, 41); ctx.fillStyle = "#94a3b8"; ctx.font = "800 13px system-ui"; ctx.fillText(`HP: ${stageHp(state.level)}`, 142, 40); ctx.fillText(`Блоков: ${state.bricks.length}`, 225, 40); ctx.fillText(`Осколки: ${Math.floor(state.fragments)}`, 345, 40); for (const brick of state.bricks) { const ratio = clamp(brick.hp / brick.max, 0, 1); rr(brick.x, brick.y, brick.w, brick.h, 7); ctx.fillStyle = brick.frozen > 0 ? "#bae6fd" : brick.color; ctx.shadowColor = brick.poison > 0 ? "#84cc16" : brick.color; ctx.shadowBlur = brick.poison > 0 ? 13 : 7; ctx.fill(); ctx.shadowBlur = 0; rr(brick.x + 4, brick.y + brick.h - 7, (brick.w - 8) * ratio, 4, 4); ctx.fillStyle = ratio > 0.35 ? "rgba(255,255,255,.86)" : "rgba(255,77,109,.95)"; ctx.fill(); } for (const ball of state.balls) { const stats = formStats(ball); ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.r + 9, 0, Math.PI * 2); ctx.fillStyle = `${ball.color}33`; ctx.fill(); ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.r, 0, Math.PI * 2); ctx.fillStyle = ball.color; ctx.fill(); ctx.strokeStyle = ball.pendingEvolution ? "#facc15" : (rarityInfo[stats.rarity]?.color || "#fff"); ctx.lineWidth = ball.pendingEvolution ? 3 : 2; ctx.stroke(); ctx.lineWidth = 1; ctx.fillStyle = "#020617"; ctx.font = "900 10px system-ui"; ctx.fillText(ball.level, ball.x - 4, ball.y + 4); if (ball.form === "sniper") { const target = state.bricks[0]; if (target) { ctx.strokeStyle = "rgba(229,231,235,.18)"; ctx.beginPath(); ctx.moveTo(ball.x, ball.y); ctx.lineTo(target.x + target.w / 2, target.y + target.h / 2); ctx.stroke(); } } } }

  function prestigeReward() { if (state.level < 10) return 0; return Math.max(1, Math.floor((Math.pow(state.level - 9, 0.72) + state.level / 180) * (1 + metaEffects().prestigeBoost))); }
  function performPrestige() { const reward = prestigeReward(); if (reward <= 0) return; const meta = getMeta(); if (metaEffects().bank) meta.bankedFragments = Math.floor(state.fragments * 0.1); meta.cores = safeNum(meta.cores) + reward; setMeta(meta); localStorage.removeItem(RUN_KEY); newRun(); save(true); renderAllUI(true); }
  function buyMeta(id) { const meta = getMeta(); const node = metaNodes.find((item) => item.id === id); if (!node || !metaUnlocked(meta, node)) return; const level = metaRank(meta, id); if (level >= node.max) return; const cost = metaNodeCost(node, level); if (meta.cores < cost) return; meta.cores -= cost; meta.spent = safeNum(meta.spent) + cost; meta.nodes[id] = level + 1; setMeta(meta); for (const ball of state.balls) ball.dmg = damageFor(ball); renderAllUI(true); }
  function save(force = false) { if (!force && frame - lastSaveFrame < 90) return; lastSaveFrame = frame; localStorage.setItem(RUN_KEY, JSON.stringify({ level: state.level, fragments: state.fragments, total: state.total, upgrades: state.upgrades, balls: state.balls })); }
  function load() { try { const data = JSON.parse(localStorage.getItem(RUN_KEY)); if (!data) return false; state.level = data.level ?? 1; state.fragments = data.fragments ?? 0; state.total = data.total ?? 0; state.upgrades = data.upgrades ?? { damage: 1, speed: 0, xp: 0 }; state.upgrades.damage = Math.max(1, state.upgrades.damage || 0); state.balls = (data.balls ?? []).map((ball, index) => makeBall(ball.id ?? index + 1, index, ball)); if (state.balls.length === 0) state.balls = [makeBall(1, 0), makeBall(2, 1)]; generateBricks(); log("Сохранение загружено."); return true; } catch { return false; } }
  function newRun() { const meta = getMeta(); const eff = metaEffects(); state.level = eff.startLevel || 1; state.fragments = 420 + (eff.startFragments || 0) + (meta.bankedFragments || 0); state.total = 0; state.upgrades = { damage: 1, speed: 0, xp: 0 }; state.balls = []; if (meta.bankedFragments) { meta.bankedFragments = 0; setMeta(meta); } const count = 2 + (eff.starterBalls || 0) + (eff.startRare ? 1 : 0) + (eff.startEpic ? 1 : 0) + (eff.startLegendary ? 1 : 0); for (let index = 0; index < count; index += 1) state.balls.push(makeBall(index + 1, index)); let starterIndex = 0; if (eff.startLegendary) forceBallForm(state.balls[starterIndex++], pickStarterForm("legendary", 2)); if (eff.startEpic) forceBallForm(state.balls[starterIndex++], pickStarterForm("epic", 1)); if (eff.startRare) forceBallForm(state.balls[starterIndex++], pickStarterForm("rare", 0)); generateBricks(); log("Новый забег запущен."); }
  function nextEvolutionDistance(ball) { if (isEvolutionLocked(ball)) return -1000000 + ball.level; const next = EVO_LEVELS.find((value) => value > ball.level) || 1000; const progress = ball.xp / Math.max(1, ball.need); return next - ball.level - progress; }

  function renderSummary() { setText("level", state.level); setText("hp", stageHp(state.level)); setText("count", state.bricks.length); setText("frags", Math.floor(state.fragments)); setText("pauseBtn", state.paused ? "Продолжить" : "Пауза"); }
  function renderTypes() { setHTML("types", activeTypes().map((type) => `<small><span class="dot" style="background:${type.color}"></span><b>${type.name}</b> — ${type.info}</small>`).join("")); }
  function renderBalls() { const sorted = [...state.balls].sort((a, b) => nextEvolutionDistance(a) - nextEvolutionDistance(b) || b.level - a.level || a.id - b.id); const html = sorted.map((ball) => { const locked = ball.pendingEvolution || pendingMilestone(ball); const stats = formStats(ball); const rarity = ball.form === "basic" ? "" : `${rarityInfo[stats.rarity].label} · `; const formLabel = ball.formName || stats.name || "Базовый"; const berserk = ball.form === "berserk" ? ` · Разгон +${Math.round((ball.berserkSpeed || 0) * 100)}%` : ""; return `<div class="ball-card ${locked ? "evo-needed" : ""}"><b>Шар-${ball.id}</b><small>${rarity}${formLabel} · Ур. ${ball.level} · Эво ${ball.evo} · Урон ${ball.dmg} · Скорость x${totalSpeed(ball).toFixed(2)}${berserk} · XP ${locked ? "СТОП" : `${Math.floor(ball.xp)}/${ball.need}`}</small><small class="tech-hint"><b>Механика:</b> ${stats.role}. ${stats.desc}</small>${locked ? `<button class="evo-btn" data-evolve-ball="${ball.id}">${ball.form === "basic" ? "Выбрать архетип" : "Усилить архетип"}</button>` : ""}</div>`; }).join(""); setHTML("balls", html); }
  function renderUpgrades() { const html = [["damage", "Урон", upgradePower(effectiveUpgrade("damage"), "damage"), "Увеличивает общий множитель урона всех шаров в текущем забеге."], ["speed", "Скорость", upgradePower(effectiveUpgrade("speed"), "speed"), "Увеличивает скорость движения всех шаров в текущем забеге."], ["xp", "Опыт", upgradePower(effectiveUpgrade("xp"), "xp"), "Увеличивает XP, который шары получают за разрушение блоков."]].map(([key, name, power, info]) => `<button class="buy" data-upgrade="${key}"><b>${name} x${power}</b> — ${upgradeCost(key)} оск.<small class="tech-hint">${info}</small></button>`).join("") + `<button class="buy" data-action="ball"><b>Новый шар</b> — ${ballCost()} оск.<small class="tech-hint">Добавляет ещё один шар в текущий забег. Цена растёт от количества шаров.</small></button>`; setHTML("upgrades", html); }
  function renderLog() { setHTML("log", state.log.slice(0, 9).map((line) => `<small>${line}</small>`).join("")); }
  function renderMeta() { const meta = getMeta(); const reward = prestigeReward(); const html = `<div class="prestige-box"><b class="meta-badge">Ядра: ${meta.cores} · Потрачено: ${meta.spent || 0}</b><small>Сингулярность сбрасывает текущий забег и даёт ядра за достигнутый этап. Доступна с 10 этапа.</small><button class="prestige-btn" data-prestige ${reward <= 0 ? "disabled" : ""}>Сингулярность: +${reward} ядер</button></div><div class="meta-tree">${metaNodes.map((node) => { const level = metaRank(meta, node.id); const unlocked = metaUnlocked(meta, node); const maxed = level >= node.max; const cost = metaNodeCost(node, level); return `<div class="meta-node ${node.type === "extra" ? "extra" : ""} ${!unlocked ? "locked" : ""} ${maxed ? "maxed" : ""}"><b>${node.name} ${node.type === "extra" ? "◆" : ""}</b><small>Слой ${node.row} · Ранг ${level}/${node.max}</small><small>${node.desc}</small>${node.req ? `<small>Требуется: ${node.req.join(", ")}</small>` : ""}<button data-meta-node="${node.id}" ${!unlocked || maxed || meta.cores < cost ? "disabled" : ""}>${maxed ? "Максимум" : `Купить за ${cost}`}</button></div>`; }).join("")}</div>`; setHTML("meta", html); }
  function renderAllUI(force = false) { if (force) uiCache.clear(); renderSummary(); renderTypes(); renderBalls(); renderUpgrades(); renderMeta(); renderLog(); }
  function buyUpgrade(key) { const cost = upgradeCost(key); if (state.fragments < cost) return; state.fragments -= cost; state.upgrades[key] = (state.upgrades[key] || 0) + 1; for (const ball of state.balls) ball.dmg = damageFor(ball); log(`Улучшение куплено: ${key}.`); renderAllUI(true); }
  function buyBall() { const cost = ballCost(); if (state.fragments < cost) return; state.fragments -= cost; const id = Math.max(0, ...state.balls.map((ball) => ball.id)) + 1; state.balls.push(makeBall(id, state.balls.length)); log(`Добавлен Шар-${id}.`); renderAllUI(true); }
  function bindUi() { el("pauseBtn").onclick = () => { state.paused = !state.paused; renderSummary(); }; el("resetBtn").onclick = () => { localStorage.removeItem(RUN_KEY); newRun(); save(true); renderAllUI(true); }; el("upgrades").addEventListener("pointerdown", (event) => { const button = event.target.closest("button"); if (!button) return; event.preventDefault(); if (button.dataset.upgrade) buyUpgrade(button.dataset.upgrade); if (button.dataset.action === "ball") buyBall(); }); el("balls").addEventListener("pointerdown", (event) => { const button = event.target.closest("[data-evolve-ball]"); if (!button) return; event.preventDefault(); showEvolution(Number(button.dataset.evolveBall)); }); document.addEventListener("pointerdown", (event) => { const prestige = event.target.closest("[data-prestige]"); if (prestige && !prestige.disabled) { event.preventDefault(); performPrestige(); return; } const node = event.target.closest("[data-meta-node]"); if (node && !node.disabled) { event.preventDefault(); buyMeta(node.dataset.metaNode); } }); canvas.style.cursor = "crosshair"; canvas.addEventListener("pointerdown", (event) => { const rect = canvas.getBoundingClientRect(); const x = (event.clientX - rect.left) * (W / rect.width); const y = (event.clientY - rect.top) * (H / rect.height); manualHitAt(x, y); }); }
  function loop() { frame += 1; step(); draw(); if (frame % 12 === 0) renderAllUI(false); save(false); requestAnimationFrame(loop); }

  function injectV10Style() { const style = document.createElement("style"); style.textContent = `.tech-hint{display:block;margin-top:6px;color:#cbd5e1;font-size:11px;line-height:1.35;font-weight:750}.evo-choice small b{color:#fff}#upgrades .buy{text-align:left}`; document.head.appendChild(style); }

  injectV10Style();
  if (!load()) newRun();
  bindUi();
  renderAllUI(true);
  draw();
  loop();
})();
