(() => {
  const W = 980, H = 650;
  const RUN_KEY = "brick_block_idle_run_v7";
  const META_KEY = "brick_block_idle_meta_v3";
  const canvas = document.getElementById("game");
  const ctx = canvas.getContext("2d");
  const milestones = [10, 25, 50, 100, 200, 500, 1000];
  const forms = [
    { key: "plasma", name: "Плазма", color: "#ff4d6d", desc: "При ударе наносит слабый урон соседним блокам." },
    { key: "storm", name: "Гроза", color: "#f9f871", desc: "После добивания бьёт цепной молнией по случайным блокам." },
    { key: "drill", name: "Бур", color: "#ff9f1c", desc: "Лучше пробивает броню, щиты и тяжёлые блоки." },
    { key: "crit", name: "Крит", color: "#b517ff", desc: "Имеет шанс нанести усиленный удар." },
    { key: "comet", name: "Комета", color: "#2ec4b6", desc: "Часть скорости превращается в дополнительный урон." },
    { key: "collector", name: "Сборщик", color: "#60a5fa", desc: "Получает больше опыта и осколков." }
  ];
  const brickTypes = [
    { key: "normal", name: "Обычный", color: "#4cc9f0", min: 1, weight: 100, reward: 1 },
    { key: "armored", name: "Броня", color: "#94a3b8", min: 5, weight: 14, reward: 1.25 },
    { key: "volatile", name: "Нестабильный", color: "#ff9f1c", min: 10, weight: 8, reward: 1.15 },
    { key: "regen", name: "Живой", color: "#2ec4b6", min: 18, weight: 8, reward: 1.35 },
    { key: "shield", name: "Щит", color: "#b517ff", min: 25, weight: 7, reward: 1.5 },
    { key: "heavy", name: "Тяжёлый", color: "#ff4d6d", min: 40, weight: 5, reward: 1.75 }
  ];
  const metaNodes = [
    { id: "dmg1", row: 1, name: "Калибровка урона I", type: "normal", max: 5, cost: 1, effect: { damage: 1 }, desc: "+1 постоянный уровень урона." },
    { id: "spd1", row: 1, name: "Магнитный разгон I", type: "normal", max: 4, cost: 1, effect: { speed: 1 }, desc: "+1 постоянный уровень скорости." },
    { id: "xp1", row: 1, name: "Память ядра I", type: "normal", max: 4, cost: 1, effect: { xp: 1 }, desc: "+1 постоянный уровень опыта." },
    { id: "frag1", row: 1, name: "Стартовый запас I", type: "normal", max: 5, cost: 1, effect: { startFragments: 40 }, desc: "+40 стартовых осколков." },
    { id: "firstExtra", row: 2, name: "Экстра: стартовый импульс", type: "extra", max: 1, cost: 4, req: ["dmg1", "frag1"], effect: { startFragments: 180, damage: 1 }, desc: "Быстрее старт нового забега." },
    { id: "dmg2", row: 3, name: "Калибровка урона II", type: "normal", max: 7, cost: 2, req: ["dmg1"], effect: { damage: 1 }, desc: "Второй слой постоянного урона." },
    { id: "spd2", row: 3, name: "Магнитный разгон II", type: "normal", max: 6, cost: 2, req: ["spd1"], effect: { speed: 1 }, desc: "Второй слой постоянной скорости." },
    { id: "xp2", row: 3, name: "Память ядра II", type: "normal", max: 6, cost: 2, req: ["xp1"], effect: { xp: 1 }, desc: "Второй слой постоянного опыта." },
    { id: "frag2", row: 3, name: "Стартовый запас II", type: "normal", max: 6, cost: 2, req: ["frag1"], effect: { startFragments: 70 }, desc: "+70 стартовых осколков." },
    { id: "autoEvolution", row: 4, name: "Экстра: автоэволюция", type: "extra", max: 1, cost: 7, req: ["xp2"], effect: { autoEvolution: 1 }, desc: "Автоматически выбирает первую форму эволюции." },
    { id: "dmg3", row: 5, name: "Калибровка урона III", type: "normal", max: 8, cost: 4, req: ["dmg2"], effect: { damage: 1 }, desc: "Поздний слой урона." },
    { id: "spd3", row: 5, name: "Магнитный разгон III", type: "normal", max: 7, cost: 4, req: ["spd2"], effect: { speed: 1 }, desc: "Поздний слой скорости." },
    { id: "xp3", row: 5, name: "Память ядра III", type: "normal", max: 8, cost: 4, req: ["xp2"], effect: { xp: 1 }, desc: "Поздний слой опыта." },
    { id: "starterBall3", row: 6, name: "Экстра: третий стартовый шар", type: "extra", max: 1, cost: 12, req: ["firstExtra", "dmg2"], effect: { starterBalls: 1 }, desc: "Старт с третьим шаром." },
    { id: "prestige1", row: 7, name: "Резонанс сингулярности I", type: "normal", max: 5, cost: 5, req: ["autoEvolution"], effect: { prestigeBoost: 0.08 }, desc: "+8% ядер за ранг." },
    { id: "discount1", row: 7, name: "Стабилизация цен I", type: "normal", max: 5, cost: 5, req: ["starterBall3"], effect: { discount: 0.03 }, desc: "-3% к цене временных апгрейдов за ранг." },
    { id: "stageSkip1", row: 8, name: "Экстра: пропуск разгона", type: "extra", max: 1, cost: 18, req: ["prestige1", "discount1"], effect: { startLevel: 3 }, desc: "Старт с 3 этапа." },
    { id: "dmg4", row: 9, name: "Калибровка урона IV", type: "normal", max: 10, cost: 8, req: ["dmg3"], effect: { damage: 1 }, desc: "Глубокий слой урона." },
    { id: "spd4", row: 9, name: "Магнитный разгон IV", type: "normal", max: 8, cost: 8, req: ["spd3"], effect: { speed: 1 }, desc: "Глубокий слой скорости." },
    { id: "xp4", row: 9, name: "Память ядра IV", type: "normal", max: 10, cost: 8, req: ["xp3"], effect: { xp: 1 }, desc: "Глубокий слой опыта." },
    { id: "starterBall4", row: 10, name: "Экстра: четвёртый стартовый шар", type: "extra", max: 1, cost: 28, req: ["starterBall3", "dmg4"], effect: { starterBalls: 2 }, desc: "Старт с четырьмя шарами." },
    { id: "prestige2", row: 11, name: "Резонанс сингулярности II", type: "normal", max: 8, cost: 10, req: ["prestige1"], effect: { prestigeBoost: 0.1 }, desc: "+10% ядер за ранг." },
    { id: "stageSkip2", row: 12, name: "Экстра: боевой старт", type: "extra", max: 1, cost: 42, req: ["stageSkip1", "prestige2"], effect: { startLevel: 6, startFragments: 600 }, desc: "Старт с 6 этапа и запасом осколков." },
    { id: "coreBank", row: 12, name: "Экстра: банк ядра", type: "extra", max: 1, cost: 55, req: ["discount1", "prestige2"], effect: { bank: 1 }, desc: "10% осколков переходят в следующий забег." }
  ];

  const el = (id) => document.getElementById(id);
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const state = { level: 1, fragments: 0, total: 0, paused: false, bricks: [], balls: [], upgrades: { damage: 0, speed: 0, xp: 0 }, log: ["v7: игра и мета объединены."] };
  let frame = 0;

  function rng(seed) { let v = seed % 2147483647; if (v <= 0) v += 2147483646; return () => { v = (v * 16807) % 2147483647; return (v - 1) / 2147483646; }; }
  function log(text) { state.log = [text, ...state.log].slice(0, 8); }
  function getMeta() { try { return JSON.parse(localStorage.getItem(META_KEY)) || { cores: 0, spent: 0, nodes: {}, bankedFragments: 0 }; } catch { return { cores: 0, spent: 0, nodes: {}, bankedFragments: 0 }; } }
  function setMeta(meta) { localStorage.setItem(META_KEY, JSON.stringify(meta)); }
  function rank(meta, id) { return meta.nodes[id] || 0; }
  function metaUnlocked(meta, node) { return !node.req || node.req.every((id) => rank(meta, id) > 0); }
  function metaNodeCost(node, level) { return Math.ceil(node.cost * Math.pow(1.62, level)); }
  function metaEffects() {
    const meta = getMeta();
    const out = { damage: 0, speed: 0, xp: 0, startFragments: 0, autoEvolution: 0, starterBalls: 0, prestigeBoost: 0, discount: 0, startLevel: 1, bank: 0 };
    for (const node of metaNodes) {
      const level = rank(meta, node.id);
      if (!level) continue;
      for (const [key, value] of Object.entries(node.effect)) {
        if (key === "startLevel") out.startLevel = Math.max(out.startLevel, value);
        else if (key === "starterBalls") out.starterBalls = Math.max(out.starterBalls, value);
        else if (key === "autoEvolution" || key === "bank") out[key] = Math.max(out[key], value);
        else out[key] += value * level;
      }
    }
    return out;
  }
  function activeTypes() { return brickTypes.filter((t) => state.level >= t.min); }
  function effectiveUpgrade(key) { const eff = metaEffects(); return (state.upgrades[key] || 0) + (eff[key] || 0); }
  function stageHp(level) { return Math.max(1, Math.floor(level + Math.pow(Math.max(0, level - 3), 1.42) * 2.4 + Math.pow(Math.max(0, level - 15), 1.86) * 0.9)); }
  function brickReward(level, typeReward) { return Math.ceil((1.2 + level * 0.42 + Math.pow(level, 1.04) * 0.22) * typeReward); }
  function upgradePower(level, kind = "generic") { if (level <= 0) return 1; const linear = kind === "speed" ? 0.34 : kind === "xp" ? 0.38 : 0.46; const curve = kind === "speed" ? 0.08 : kind === "xp" ? 0.1 : 0.14; return +(1 + level * linear + (Math.pow(level, 1.28) - level) * curve).toFixed(2); }
  function xpNeed(level) { if (level <= 1) return 55; return Math.floor(55 + level * 34 + Math.pow(level, 2.02) * 32 + Math.pow(Math.max(0, level - 8), 2.25) * 42 + (milestones.includes(level) ? level * 140 : 0)); }
  function pendingMilestone(ball) { return milestones.find((m) => ball.level >= m && !ball.evolved.includes(m)) || null; }
  function isEvolutionLocked(ball) { return Boolean(ball.pendingEvolution || pendingMilestone(ball)); }
  function damageFor(ball) { const base = 1 + (ball.level - 1) * 0.25 + Math.pow(ball.level - 1, 1.05) * 0.045; const evo = 1 + ball.evo * 0.14 + Math.pow(ball.evo, 1.15) * 0.025; return +(base * evo * upgradePower(effectiveUpgrade("damage"), "damage")).toFixed(2); }
  function personalSpeed(ball) { const comet = ball.form === "comet" ? ball.evo * 0.012 : 0; return clamp(1 + (ball.level - 1) * 0.0018 + ball.evo * 0.014 + comet, 1, 1.95); }
  function totalSpeed(ball) { return personalSpeed(ball) * upgradePower(effectiveUpgrade("speed"), "speed"); }
  function xpMult() { return upgradePower(effectiveUpgrade("xp"), "xp"); }
  function xpGain(brick, ball) { if (isEvolutionLocked(ball)) return 0; const bonus = ball.form === "collector" ? 1 + ball.evo * 0.06 : 1; return Math.max(1, Math.ceil(brick.xp * 0.08 * xpMult() * bonus)); }
  function fragGain(brick, ball) { const bonus = ball.form === "collector" ? 1 + ball.evo * 0.08 : 1; return Math.max(1, Math.ceil(brick.xp * 0.34 * bonus)); }
  function discount() { return clamp(metaEffects().discount || 0, 0, 0.65); }
  function ballCost() { return Math.floor(320 * Math.pow(2.15, Math.max(0, state.balls.length - 2)) * (1 - discount())); }
  function upgradeCost(key) { const base = key === "damage" ? 280 : key === "speed" ? 380 : 420; const growth = key === "damage" ? 2.28 : key === "speed" ? 2.45 : 2.55; const level = state.upgrades[key] || 0; return Math.floor(base * Math.pow(growth, level + Math.pow(level, 1.36) * 0.82) * (1 - discount())); }
  function normalize(ball) { const len = Math.hypot(ball.dx, ball.dy) || 1; ball.dx /= len; ball.dy /= len; }
  function makeBall(id, index, saved) { const angle = -Math.PI / 4 - index * 0.33; const ball = { id, level: 1, x: W / 2 + index * 34, y: H - 82 - index * 18, dx: Math.cos(angle) * (index % 2 ? -1 : 1), dy: -Math.abs(Math.sin(angle)), r: 9, xp: 0, need: 55, kills: 0, hits: 0, evo: 0, form: "basic", formName: "Базовый", color: "#4cc9f0", evolved: [], pendingEvolution: null, ...(saved || {}) }; if (typeof ball.dx !== "number" || typeof ball.dy !== "number") { ball.dx = Math.cos(angle); ball.dy = -Math.abs(Math.sin(angle)); } normalize(ball); ball.need = xpNeed(ball.level); ball.pendingEvolution = ball.pendingEvolution || pendingMilestone(ball); ball.dmg = damageFor(ball); return ball; }
  function pattern(row, col, rows, cols) { if (state.level === 1) return true; if (row === 0 || row === rows - 1) return true; const p = (state.level - 1) % 8; const cx = (cols - 1) / 2; const cy = (rows - 1) / 2; const dx = col - cx; const dy = row - cy; const d = Math.hypot(dx, dy); const a = Math.atan2(dy, dx); if (p === 0) return !((col + state.level) % 5 === 0 && row % 4 !== 0); if (p === 1) return (row + col + state.level) % 6 !== 0 && (row * 2 + col + state.level) % 11 !== 0; if (p === 2) return Math.abs((d + state.level * 0.35) % 4) > 0.85; if (p === 3) return Math.hypot(col - cols * 0.32, row - rows * 0.48) > 2.4 && Math.hypot(col - cols * 0.68, row - rows * 0.48) > 2.4; if (p === 4) return row % 4 !== 2 || (col + state.level) % 4 !== 0; if (p === 5) return Math.abs(Math.sin(a * 2.4 + d * 0.68 + state.level * 0.25)) > 0.26; if (p === 6) return (row + col * 2 + state.level) % 7 !== 0; return rng(state.level * 999 + row * 13 + col)() > 0.14; }
  function pickType(row, col, random) { const pool = activeTypes(); if (pool.length === 1) return pool[0]; const weighted = pool.map((type) => ({ type, weight: type.key === "normal" ? Math.max(42, type.weight - state.level * 0.65) : type.weight + ((row * 11 + col * 7 + state.level) % 9) * 0.2 })); let roll = random() * weighted.reduce((sum, item) => sum + item.weight, 0); for (const item of weighted) { roll -= item.weight; if (roll <= 0) return item.type; } return pool[0]; }
  function generateBricks() { const cols = clamp(18 + Math.floor(state.level / 10), 18, 24); const gap = 5; const marginX = 18; const top = 70; const brickH = 22; const rows = Math.floor((H - 24 - top + gap) / (brickH + gap)); const brickW = (W - marginX * 2 - gap * (cols - 1)) / cols; const random = rng(state.level * 9973 + 41); const hp = stageHp(state.level); state.bricks = []; for (let row = 0; row < rows; row += 1) for (let col = 0; col < cols; col += 1) { if (!pattern(row, col, rows, cols)) continue; const type = pickType(row, col, random); state.bricks.push({ x: marginX + col * (brickW + gap), y: top + row * (brickH + gap), w: brickW, h: brickH, hp, max: hp, xp: brickReward(state.level, type.reward), type: type.key, name: type.name, color: type.color }); } }
  function chooseThreeForms(ball) { const random = rng(Date.now() + ball.id * 1337 + ball.level * 17); const pool = [...forms]; const result = []; while (result.length < 3 && pool.length) result.push(pool.splice(Math.floor(random() * pool.length), 1)[0]); return result; }
  function applyEvolution(ballId, formKey) { const ball = state.balls.find((item) => item.id === ballId); const form = forms.find((item) => item.key === formKey); if (!ball || !form) return; const milestone = ball.pendingEvolution || pendingMilestone(ball); if (!milestone) return; ball.evo += 1; ball.form = form.key; ball.formName = form.name; ball.color = form.color; ball.r = 9 + Math.min(8, ball.evo * 0.85); ball.evolved.push(milestone); ball.pendingEvolution = null; ball.xp = 0; ball.need = xpNeed(ball.level); ball.dmg = damageFor(ball); log(`Шар-${ball.id} эволюционировал: ${form.name}.`); }
  function showEvolution(ballId) { const ball = state.balls.find((item) => item.id === ballId); if (!ball) return; const milestone = ball.pendingEvolution || pendingMilestone(ball); if (!milestone) return; if (metaEffects().autoEvolution) { applyEvolution(ball.id, chooseThreeForms(ball)[0].key); return; } ball.pendingEvolution = milestone; const choices = chooseThreeForms(ball); document.querySelector(".evo-modal")?.remove(); const modal = document.createElement("div"); modal.className = "evo-modal"; modal.innerHTML = `<div class="evo-box"><h2>Эволюция Шара-${ball.id}</h2><p>Шар достиг ${milestone} уровня. Опыт остановлен до выбора формы.</p><div class="evo-grid">${choices.map((form) => `<button class="evo-choice" data-ball="${ball.id}" data-form="${form.key}"><span class="dot" style="background:${form.color}"></span><b>${form.name}</b><small>${form.desc}</small></button>`).join("")}</div><button class="control evo-close">Позже</button></div>`; modal.addEventListener("pointerdown", (event) => { const choice = event.target.closest(".evo-choice"); if (choice) { applyEvolution(Number(choice.dataset.ball), choice.dataset.form); modal.remove(); ui(); return; } if (event.target.closest(".evo-close")) modal.remove(); }); document.body.appendChild(modal); }
  function reward(ball, brick) { state.fragments += fragGain(brick, ball); state.total += 1; ball.kills += 1; if (isEvolutionLocked(ball)) { if (metaEffects().autoEvolution) showEvolution(ball.id); return; } ball.xp += xpGain(brick, ball); while (!isEvolutionLocked(ball) && ball.xp >= ball.need) { ball.xp -= ball.need; ball.level += 1; ball.need = xpNeed(ball.level); ball.dmg = damageFor(ball); log(`Шар-${ball.id}: ${ball.level} ур.`); const milestone = pendingMilestone(ball); if (milestone) { ball.pendingEvolution = milestone; ball.xp = 0; log(`Шар-${ball.id} ждёт эволюцию ${milestone} ур.`); if (metaEffects().autoEvolution) showEvolution(ball.id); break; } } }
  function damageMult(ball, brick, source) { let m = 1; if (brick.type === "armored") m = source === "direct" ? 0.55 : 0.75; if (brick.type === "regen") m = source === "direct" ? 0.85 : 0.7; if (brick.type === "shield") m = source === "direct" ? 0.8 : 0.35; if (brick.type === "heavy") m = source === "direct" ? 0.45 : 0.58; if (ball.form === "drill" && source === "direct" && m < 1) m += (1 - m) * clamp(0.35 + ball.evo * 0.08, 0.35, 0.82); return m; }
  function dealDamage(index, amount, ball, source = "direct") { const brick = state.bricks[index]; if (!brick || !ball) return false; brick.hp -= amount * damageMult(ball, brick, source); if (brick.hp > 0) return false; const destroyed = state.bricks.splice(index, 1)[0]; if (!destroyed) return false; reward(ball, destroyed); if (destroyed.type === "volatile") { const cx = destroyed.x + destroyed.w / 2, cy = destroyed.y + destroyed.h / 2; const targets = state.bricks.map((b, i) => ({ i, d: Math.hypot(b.x + b.w / 2 - cx, b.y + b.h / 2 - cy) })).filter((item) => item.d <= 62).map((item) => item.i).sort((a, b) => b - a); for (const target of targets) dealDamage(target, Math.max(1, stageHp(state.level) * 0.12 + ball.dmg * 0.12), ball, "explosion"); } return true; }
  function hitDamage(ball, brick) { let amount = ball.dmg; if (ball.form === "crit" && Math.random() < clamp(0.1 + ball.evo * 0.025, 0.1, 0.36)) amount *= 1.5 + ball.evo * 0.1; if (ball.form === "drill" && brick.hp / brick.max > 0.5) amount *= 1.12 + ball.evo * 0.08; if (ball.form === "comet") amount *= 1 + Math.min(0.55, (personalSpeed(ball) - 1) * 0.16); return amount; }
  function collide(ball, brick) { const nx = clamp(ball.x, brick.x, brick.x + brick.w); const ny = clamp(ball.y, brick.y, brick.y + brick.h); const dx = ball.x - nx; const dy = ball.y - ny; return dx * dx + dy * dy <= ball.r * ball.r; }
  function step() { if (state.paused) return; for (const brick of state.bricks) if (brick.type === "regen" && brick.hp < brick.max) brick.hp = Math.min(brick.max, brick.hp + Math.max(0.01, stageHp(state.level) * 0.001)); for (const ball of state.balls) { const move = 1.15 * totalSpeed(ball); ball.x += ball.dx * move; ball.y += ball.dy * move; if (ball.x - ball.r <= 0 || ball.x + ball.r >= W) { ball.dx *= -1; ball.x = clamp(ball.x, ball.r, W - ball.r); } if (ball.y - ball.r <= 0 || ball.y + ball.r >= H) { ball.dy *= -1; ball.y = clamp(ball.y, ball.r, H - ball.r); } normalize(ball); for (let i = state.bricks.length - 1; i >= 0; i -= 1) { const brick = state.bricks[i]; if (!brick || !collide(ball, brick)) continue; const prevX = ball.x - ball.dx * move; if (prevX < brick.x || prevX > brick.x + brick.w) ball.dx *= -1; else ball.dy *= -1; normalize(ball); ball.hits += 1; const center = { x: brick.x + brick.w / 2, y: brick.y + brick.h / 2 }; const destroyed = dealDamage(i, hitDamage(ball, brick), ball); if (ball.form === "plasma" && ball.evo > 0) { const targets = state.bricks.map((b, j) => ({ j, d: Math.hypot(b.x + b.w / 2 - center.x, b.y + b.h / 2 - center.y) })).filter((item) => item.d <= 54 + ball.evo * 8).map((item) => item.j).sort((a, b) => b - a); for (const target of targets) dealDamage(target, ball.dmg * (0.08 + ball.evo * 0.015), ball, "splash"); } if (ball.form === "storm" && destroyed && state.bricks.length > 0) { const jumps = clamp(1 + Math.floor(ball.evo / 3), 1, 4); for (let n = 0; n < jumps && state.bricks.length > 0; n += 1) dealDamage(Math.floor(Math.random() * state.bricks.length), ball.dmg * (0.36 + ball.evo * 0.045), ball, "chain"); } break; } } if (state.bricks.length === 0) { state.level += 1; generateBricks(); for (const ball of state.balls) normalize(ball); log(`Открыт этап ${state.level}. HP блока: ${stageHp(state.level)}.`); } }
  function rr(x, y, w, h, r) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); }
  function draw() { ctx.clearRect(0, 0, W, H); const bg = ctx.createLinearGradient(0, 0, 0, H); bg.addColorStop(0, "#070b18"); bg.addColorStop(1, "#111827"); ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H); ctx.fillStyle = "rgba(148,163,184,.08)"; for (let x = 22; x < W; x += 42) for (let y = 76; y < H; y += 42) { ctx.beginPath(); ctx.arc(x, y, 1.45, 0, Math.PI * 2); ctx.fill(); } rr(22, 18, W - 44, 42, 16); ctx.fillStyle = "rgba(15,23,42,.82)"; ctx.fill(); ctx.fillStyle = "#fff"; ctx.font = "900 18px system-ui"; ctx.fillText(`Этап ${state.level}`, 42, 45); ctx.fillStyle = "#94a3b8"; ctx.font = "800 13px system-ui"; ctx.fillText(`HP: ${stageHp(state.level)}`, 142, 44); ctx.fillText(`Блоков: ${state.bricks.length}`, 225, 44); ctx.fillText(`Осколки: ${Math.floor(state.fragments)}`, 345, 44); for (const brick of state.bricks) { const ratio = clamp(brick.hp / brick.max, 0, 1); rr(brick.x, brick.y, brick.w, brick.h, 8); ctx.fillStyle = brick.color; ctx.shadowColor = brick.color; ctx.shadowBlur = 8; ctx.fill(); ctx.shadowBlur = 0; rr(brick.x + 5, brick.y + brick.h - 8, (brick.w - 10) * ratio, 4, 4); ctx.fillStyle = ratio > 0.35 ? "rgba(255,255,255,.86)" : "rgba(255,77,109,.95)"; ctx.fill(); } for (const ball of state.balls) { ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.r + 9, 0, Math.PI * 2); ctx.fillStyle = `${ball.color}33`; ctx.fill(); ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.r, 0, Math.PI * 2); ctx.fillStyle = ball.color; ctx.fill(); ctx.strokeStyle = ball.pendingEvolution ? "#facc15" : "#fff"; ctx.lineWidth = ball.pendingEvolution ? 3 : 1; ctx.stroke(); ctx.lineWidth = 1; ctx.fillStyle = "#020617"; ctx.font = "900 10px system-ui"; ctx.fillText(ball.level, ball.x - 4, ball.y + 4); } }
  function prestigeReward() { if (state.level < 10) return 0; return Math.max(1, Math.floor(Math.pow(state.level - 9, 0.74) * (1 + metaEffects().prestigeBoost))); }
  function performPrestige() { const reward = prestigeReward(); if (reward <= 0) return; const meta = getMeta(); if (metaEffects().bank) meta.bankedFragments = Math.floor(state.fragments * 0.1); meta.cores += reward; setMeta(meta); localStorage.removeItem(RUN_KEY); location.reload(); }
  function renderMeta() { const root = el("meta"); if (!root) return; const meta = getMeta(); const reward = prestigeReward(); root.innerHTML = `<div class="prestige-box"><b class="meta-badge">Ядра: ${meta.cores} · Потрачено: ${meta.spent || 0}</b><small>Сингулярность сбрасывает забег и даёт ядра за этап. Доступна с 10 этапа.</small><button class="prestige-btn" data-prestige ${reward <= 0 ? "disabled" : ""}>Сингулярность: +${reward} ядер</button></div><div class="meta-tree">${metaNodes.map((node) => { const r = rank(meta, node.id); const unlocked = metaUnlocked(meta, node); const maxed = r >= node.max; const cost = metaNodeCost(node, r); return `<div class="meta-node ${node.type === "extra" ? "extra" : ""} ${!unlocked ? "locked" : ""} ${maxed ? "maxed" : ""}"><b>${node.name} ${node.type === "extra" ? "◆" : ""}</b><small>Слой ${node.row} · Ранг ${r}/${node.max}</small><small>${node.desc}</small>${node.req ? `<small>Требуется: ${node.req.join(", ")}</small>` : ""}<button data-meta-node="${node.id}" ${!unlocked || maxed || meta.cores < cost ? "disabled" : ""}>${maxed ? "Максимум" : `Купить за ${cost}`}</button></div>`; }).join("")}</div>`; }
  function buyMeta(id) { const meta = getMeta(); const node = metaNodes.find((item) => item.id === id); if (!node || !metaUnlocked(meta, node)) return; const r = rank(meta, id); if (r >= node.max) return; const cost = metaNodeCost(node, r); if (meta.cores < cost) return; meta.cores -= cost; meta.spent = (meta.spent || 0) + cost; meta.nodes[id] = r + 1; setMeta(meta); for (const ball of state.balls) ball.dmg = damageFor(ball); renderMeta(); ui(); }
  function save() { if (frame % 90 !== 0) return; localStorage.setItem(RUN_KEY, JSON.stringify({ level: state.level, fragments: state.fragments, total: state.total, upgrades: state.upgrades, balls: state.balls })); }
  function load() { try { const data = JSON.parse(localStorage.getItem(RUN_KEY)); if (!data) return false; state.level = data.level ?? 1; state.fragments = data.fragments ?? 0; state.total = data.total ?? 0; state.upgrades = data.upgrades ?? state.upgrades; state.balls = (data.balls ?? []).map((ball, index) => makeBall(ball.id ?? index + 1, index, ball)); if (state.balls.length === 0) state.balls = [makeBall(1, 0), makeBall(2, 1)]; generateBricks(); log("Сохранение загружено."); return true; } catch { return false; } }
  function newRun() { const meta = getMeta(); const eff = metaEffects(); state.level = eff.startLevel || 1; state.fragments = (eff.startFragments || 0) + (meta.bankedFragments || 0); if (meta.bankedFragments) { meta.bankedFragments = 0; setMeta(meta); } state.total = 0; state.upgrades = { damage: 0, speed: 0, xp: 0 }; state.balls = []; const count = 2 + (eff.starterBalls || 0); for (let i = 0; i < count; i += 1) state.balls.push(makeBall(i + 1, i)); generateBricks(); }
  function ballCard(ball) { const locked = ball.pendingEvolution || pendingMilestone(ball); const formLabel = ball.formName || forms.find((f) => f.key === ball.form)?.name || "Базовый"; return `<div class="ball-card ${locked ? "evo-needed" : ""}"><b>Шар-${ball.id}</b><small>${formLabel} · Ур. ${ball.level} · Урон ${ball.dmg} · Скорость x${totalSpeed(ball).toFixed(2)} · XP ${locked ? "СТОП" : `${Math.floor(ball.xp)}/${ball.need}`}</small>${locked ? `<button class="evo-btn" data-evolve-ball="${ball.id}">Эволюционировать</button>` : ""}</div>`; }
  function ui() { el("level").textContent = state.level; el("hp").textContent = stageHp(state.level); el("count").textContent = state.bricks.length; el("frags").textContent = Math.floor(state.fragments); el("pauseBtn").textContent = state.paused ? "Продолжить" : "Пауза"; el("types").innerHTML = activeTypes().map((type) => `<small><span class="dot" style="background:${type.color}"></span>${type.name}</small>`).join(""); el("balls").innerHTML = state.balls.map(ballCard).join(""); el("upgrades").innerHTML = [["damage", "Урон", upgradePower(effectiveUpgrade("damage"), "damage")], ["speed", "Скорость", upgradePower(effectiveUpgrade("speed"), "speed")], ["xp", "Опыт", upgradePower(effectiveUpgrade("xp"), "xp")]].map(([key, name, power]) => `<button class="buy" data-upgrade="${key}">${name} x${power} — ${upgradeCost(key)} оск.</button>`).join("") + `<button class="buy" data-action="ball">Новый шар — ${ballCost()} оск.</button>`; el("log").innerHTML = state.log.slice(0, 8).map((line) => `<small>${line}</small>`).join(""); if (frame % 16 === 0) renderMeta(); }
  function buyUpgrade(key) { const cost = upgradeCost(key); if (state.fragments < cost) return; state.fragments -= cost; state.upgrades[key] += 1; for (const ball of state.balls) ball.dmg = damageFor(ball); log(`Улучшение куплено: ${key}.`); }
  function buyBall() { const cost = ballCost(); if (state.fragments < cost) return; state.fragments -= cost; const id = Math.max(...state.balls.map((ball) => ball.id)) + 1; state.balls.push(makeBall(id, state.balls.length)); log(`Добавлен Шар-${id}.`); }
  function bindUi() { el("pauseBtn").onclick = () => { state.paused = !state.paused; ui(); }; el("resetBtn").onclick = () => { localStorage.removeItem(RUN_KEY); location.reload(); }; el("upgrades").addEventListener("pointerdown", (event) => { const button = event.target.closest("button"); if (!button) return; event.preventDefault(); if (button.dataset.upgrade) buyUpgrade(button.dataset.upgrade); if (button.dataset.action === "ball") buyBall(); ui(); }); el("balls").addEventListener("pointerdown", (event) => { const button = event.target.closest("[data-evolve-ball]"); if (!button) return; event.preventDefault(); showEvolution(Number(button.dataset.evolveBall)); }); document.addEventListener("pointerdown", (event) => { const prestige = event.target.closest("[data-prestige]"); if (prestige && !prestige.disabled) { event.preventDefault(); performPrestige(); return; } const node = event.target.closest("[data-meta-node]"); if (node && !node.disabled) { event.preventDefault(); buyMeta(node.dataset.metaNode); } }); }
  function loop() { frame += 1; step(); draw(); if (frame % 8 === 0) ui(); save(); requestAnimationFrame(loop); }
  if (!load()) newRun(); bindUi(); ui(); renderMeta(); loop();
})();
